server:
  port: 8080

spring:
  profiles:
    active: release
  application:
    name: zmn-census-web
  resources:
    static-locations: classpath:static/,file:static/


mybatis:
  type-aliases-package: com.zmn.census.action.entity
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
